import { createContext, useContext, useState, useEffect } from 'react';
import { useAuth } from './AuthContext';

const ArticleContext = createContext();

const INITIAL_ARTICLES = [
    {
        id: 1,
        title: '令和6年度 文化祭取材レポート',
        date: '2024.11.15',
        category: 'イベント',
        excerpt: '今年の文化祭は例年以上の盛り上がりを見せました。各クラスの出し物やステージ発表の裏側に迫ります。'
    },
    {
        id: 2,
        title: '新生徒会長インタビュー「これからの学校」',
        date: '2024.10.20',
        category: 'インタビュー',
        excerpt: '先日の選挙で選ばれた新生徒会長に、公約の実現に向けた具体的なプランと意気込みを聞きました。'
    },
    {
        id: 3,
        title: '部活動特集：吹奏楽部の挑戦',
        date: '2024.09.05',
        category: '部活動',
        excerpt: 'コンクール金賞を目指して練習に励む吹奏楽部。その熱気と団結力の秘密を探ります。'
    }
];

export function ArticleProvider({ children }) {
    const [articles, setArticles] = useState([]);
    const [comments, setComments] = useState([]);
    const { user } = useAuth();

    useEffect(() => {
        fetch('http://localhost:3000/articles')
            .then(res => res.json())
            .then(data => setArticles(data))
            .catch(err => console.error(err));

        fetch('http://localhost:3000/comments')
            .then(res => res.json())
            .then(data => setComments(data))
            .catch(err => console.error(err));
    }, []);

    const addArticle = async (article) => {
        try {
            const newArticle = {
                ...article,
                id: Date.now().toString(),
                date: new Date().toLocaleDateString('ja-JP').replace(/\//g, '.'),
                content: article.content || []
            };
            const res = await fetch('http://localhost:3000/articles', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${user?.token}`
                },
                body: JSON.stringify(newArticle)
            });

            if (!res.ok) {
                const errorData = await res.json().catch(() => ({ message: 'サーバーからの不明なエラー' }));
                return { success: false, message: errorData.message || '記事の追加に失敗しました。' };
            }

            const saved = await res.json();
            setArticles([saved, ...articles]);
            return { success: true, article: saved };
        } catch (error) {
            return { success: false, message: error.message };
        }
    };

    const updateArticle = async (id, updatedData) => {
        // json-server needs string ID usually if generated by date.now().toString()
        const targetId = id.toString();

        await fetch(`http://localhost:3000/articles/${targetId}`, {
            method: 'PATCH',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${user?.token}`
            },
            body: JSON.stringify(updatedData)
        });

        setArticles(articles.map(a => a.id.toString() === targetId ? { ...a, ...updatedData } : a));
    };

    const deleteArticle = async (id) => {
        const targetId = id.toString();
        await fetch(`http://localhost:3000/articles/${targetId}`, {
            method: 'DELETE',
            headers: { 'Authorization': `Bearer ${user?.token}` }
        });
        setArticles(articles.filter(a => a.id.toString() !== targetId));
    };

    const addComment = async (comment) => {
        const newComment = {
            ...comment,
            id: Date.now(),
            date: new Date().toLocaleDateString('ja-JP')
        };
        const res = await fetch('http://localhost:3000/comments', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${user?.token}`
            },
            body: JSON.stringify(newComment)
        });
        const saved = await res.json();
        setComments([...comments, saved]);
    };

    return (
        <ArticleContext.Provider value={{ articles, comments, addArticle, updateArticle, deleteArticle, addComment }}>
            {children}
        </ArticleContext.Provider>
    );
}

export const useArticles = () => useContext(ArticleContext);
